name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish-tauri:
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows portable build
          - platform: windows-latest
            args: --no-bundle
            uploadPlainBinary: true

          # Linux bundled build
          - platform: ubuntu-24.04
            args: ""
            uploadPlainBinary: false

          # macOS bundled build
          - platform: macos-latest
            args: ""
            uploadPlainBinary: false

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install frontend deps
        run: npm ci

      - name: Install Linux deps
        if: matrix.platform == 'ubuntu-24.04'
        run: |
          sudo apt update
          sudo apt install -y \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libpipewire-0.3-dev \
            libspa-0.2-dev \
            patchelf

      - name: Build + Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "Sythoria ${{ github.ref_name }}"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false

          args: ${{ matrix.args }}
          uploadPlainBinary: ${{ matrix.uploadPlainBinary }}